# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ek/control/v1/control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ek/control/v1/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65k/control/v1/control.proto\x12\rek.control.v1\"\x0e\n\x0cRebalanceReq\"\x0f\n\rRebalanceResp\"!\n\x0c\x44uplicateReq\x12\x11\n\thostnames\x18\x01 \x03(\t\"\x0f\n\rDuplicateResp\".\n\tManualReq\x12\x11\n\thostnames\x18\x01 \x03(\t\x12\x0e\n\x06layers\x18\x02 \x01(\t\"\x0c\n\nManualResp\"3\n\x0eResolveRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08slice_id\x18\x02 \x01(\t\"1\n\x0cResolveReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08slice_id\x18\x02 \x01(\t2\xdc\x01\n\x0bPlanService\x12\x46\n\tRebalance\x12\x1b.ek.control.v1.RebalanceReq\x1a\x1c.ek.control.v1.RebalanceResp\x12\x46\n\tDuplicate\x12\x1b.ek.control.v1.DuplicateReq\x1a\x1c.ek.control.v1.DuplicateResp\x12=\n\x06Manual\x12\x18.ek.control.v1.ManualReq\x1a\x19.ek.control.v1.ManualResp2Y\n\x10\x44iscoveryService\x12\x45\n\x07Resolve\x12\x1d.ek.control.v1.ResolveRequest\x1a\x1b.ek.control.v1.ResolveReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ek.control.v1.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REBALANCEREQ']._serialized_start=46
  _globals['_REBALANCEREQ']._serialized_end=60
  _globals['_REBALANCERESP']._serialized_start=62
  _globals['_REBALANCERESP']._serialized_end=77
  _globals['_DUPLICATEREQ']._serialized_start=79
  _globals['_DUPLICATEREQ']._serialized_end=112
  _globals['_DUPLICATERESP']._serialized_start=114
  _globals['_DUPLICATERESP']._serialized_end=129
  _globals['_MANUALREQ']._serialized_start=131
  _globals['_MANUALREQ']._serialized_end=177
  _globals['_MANUALRESP']._serialized_start=179
  _globals['_MANUALRESP']._serialized_end=191
  _globals['_RESOLVEREQUEST']._serialized_start=193
  _globals['_RESOLVEREQUEST']._serialized_end=244
  _globals['_RESOLVEREPLY']._serialized_start=246
  _globals['_RESOLVEREPLY']._serialized_end=295
  _globals['_PLANSERVICE']._serialized_start=298
  _globals['_PLANSERVICE']._serialized_end=518
  _globals['_DISCOVERYSERVICE']._serialized_start=520
  _globals['_DISCOVERYSERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
