# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from expertkit_torch.pbpy.ek.control.v1 import control_pb2 as ek_dot_control_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ek/control/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Rebalance = channel.unary_unary(
                '/ek.control.v1.PlanService/Rebalance',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.RebalanceReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.RebalanceResp.FromString,
                _registered_method=True)
        self.Duplicate = channel.unary_unary(
                '/ek.control.v1.PlanService/Duplicate',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.DuplicateReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.DuplicateResp.FromString,
                _registered_method=True)
        self.Manual = channel.unary_unary(
                '/ek.control.v1.PlanService/Manual',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.ManualReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.ManualResp.FromString,
                _registered_method=True)


class PlanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Rebalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Duplicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Manual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Rebalance': grpc.unary_unary_rpc_method_handler(
                    servicer.Rebalance,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.RebalanceReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.RebalanceResp.SerializeToString,
            ),
            'Duplicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Duplicate,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.DuplicateReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.DuplicateResp.SerializeToString,
            ),
            'Manual': grpc.unary_unary_rpc_method_handler(
                    servicer.Manual,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.ManualReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.ManualResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v1.PlanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v1.PlanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Rebalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.PlanService/Rebalance',
            ek_dot_control_dot_v1_dot_control__pb2.RebalanceReq.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.RebalanceResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Duplicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.PlanService/Duplicate',
            ek_dot_control_dot_v1_dot_control__pb2.DuplicateReq.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.DuplicateResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Manual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.PlanService/Manual',
            ek_dot_control_dot_v1_dot_control__pb2.ManualReq.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.ManualResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resolve = channel.unary_unary(
                '/ek.control.v1.DiscoveryService/Resolve',
                request_serializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveRequest.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveReply.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveRequest.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_control__pb2.ResolveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v1.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.DiscoveryService/Resolve',
            ek_dot_control_dot_v1_dot_control__pb2.ResolveRequest.SerializeToString,
            ek_dot_control_dot_v1_dot_control__pb2.ResolveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
