# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from expertkit_torch.pbpy.ek.control.v1 import routing_pb2 as ek_dot_control_dot_v1_dot_routing__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ek/control/v1/routing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoutingServiceStub(object):
    """RoutingService provides expert-to-worker routing information to frontends
    This enables direct frontend→worker communication without controller forwarding
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRouting = channel.unary_unary(
                '/ek.control.v1.RoutingService/GetRouting',
                request_serializer=ek_dot_control_dot_v1_dot_routing__pb2.GetRoutingReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_routing__pb2.GetRoutingResp.FromString,
                _registered_method=True)
        self.SubscribeRoutingUpdates = channel.unary_stream(
                '/ek.control.v1.RoutingService/SubscribeRoutingUpdates',
                request_serializer=ek_dot_control_dot_v1_dot_routing__pb2.SubscribeRoutingReq.SerializeToString,
                response_deserializer=ek_dot_control_dot_v1_dot_routing__pb2.RoutingUpdate.FromString,
                _registered_method=True)


class RoutingServiceServicer(object):
    """RoutingService provides expert-to-worker routing information to frontends
    This enables direct frontend→worker communication without controller forwarding
    """

    def GetRouting(self, request, context):
        """GetRouting returns the current routing table (expert_id → worker_addr)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRoutingUpdates(self, request, context):
        """SubscribeRoutingUpdates streams real-time routing changes to frontends
        Frontends should use this to stay synchronized with controller decisions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRouting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRouting,
                    request_deserializer=ek_dot_control_dot_v1_dot_routing__pb2.GetRoutingReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_routing__pb2.GetRoutingResp.SerializeToString,
            ),
            'SubscribeRoutingUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRoutingUpdates,
                    request_deserializer=ek_dot_control_dot_v1_dot_routing__pb2.SubscribeRoutingReq.FromString,
                    response_serializer=ek_dot_control_dot_v1_dot_routing__pb2.RoutingUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ek.control.v1.RoutingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ek.control.v1.RoutingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoutingService(object):
    """RoutingService provides expert-to-worker routing information to frontends
    This enables direct frontend→worker communication without controller forwarding
    """

    @staticmethod
    def GetRouting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ek.control.v1.RoutingService/GetRouting',
            ek_dot_control_dot_v1_dot_routing__pb2.GetRoutingReq.SerializeToString,
            ek_dot_control_dot_v1_dot_routing__pb2.GetRoutingResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRoutingUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ek.control.v1.RoutingService/SubscribeRoutingUpdates',
            ek_dot_control_dot_v1_dot_routing__pb2.SubscribeRoutingReq.SerializeToString,
            ek_dot_control_dot_v1_dot_routing__pb2.RoutingUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
