# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ek/control/v1/routing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ek/control/v1/routing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65k/control/v1/routing.proto\x12\rek.control.v1\"#\n\rGetRoutingReq\x12\x12\n\nexpert_ids\x18\x01 \x03(\t\"u\n\x0eWorkerEndpoint\x12\x11\n\tgrpc_addr\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x15\n\rrdma_tcp_port\x18\x03 \x01(\r\x12\x18\n\x10shm_queue_prefix\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\t\"\xad\x01\n\x0eGetRoutingResp\x12;\n\x07routing\x18\x01 \x03(\x0b\x32*.ek.control.v1.GetRoutingResp.RoutingEntry\x12\x0f\n\x07version\x18\x02 \x01(\x04\x1aM\n\x0cRoutingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.ek.control.v1.WorkerEndpoint:\x02\x38\x01\".\n\x13SubscribeRoutingReq\x12\x17\n\x0f\x63urrent_version\x18\x01 \x01(\x04\"\xcf\x01\n\rRoutingUpdate\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.ek.control.v1.RoutingUpdate.ChangeType\x12\x11\n\texpert_id\x18\x02 \x01(\t\x12/\n\x08\x65ndpoint\x18\x03 \x01(\x0b\x32\x1d.ek.control.v1.WorkerEndpoint\x12\x0f\n\x07version\x18\x04 \x01(\x04\"2\n\nChangeType\x12\t\n\x05\x41\x44\x44\x45\x44\x10\x00\x12\x0b\n\x07REMOVED\x10\x01\x12\x0c\n\x08MODIFIED\x10\x02\x32\xba\x01\n\x0eRoutingService\x12I\n\nGetRouting\x12\x1c.ek.control.v1.GetRoutingReq\x1a\x1d.ek.control.v1.GetRoutingResp\x12]\n\x17SubscribeRoutingUpdates\x12\".ek.control.v1.SubscribeRoutingReq\x1a\x1c.ek.control.v1.RoutingUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ek.control.v1.routing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETROUTINGRESP_ROUTINGENTRY']._loaded_options = None
  _globals['_GETROUTINGRESP_ROUTINGENTRY']._serialized_options = b'8\001'
  _globals['_GETROUTINGREQ']._serialized_start=46
  _globals['_GETROUTINGREQ']._serialized_end=81
  _globals['_WORKERENDPOINT']._serialized_start=83
  _globals['_WORKERENDPOINT']._serialized_end=200
  _globals['_GETROUTINGRESP']._serialized_start=203
  _globals['_GETROUTINGRESP']._serialized_end=376
  _globals['_GETROUTINGRESP_ROUTINGENTRY']._serialized_start=299
  _globals['_GETROUTINGRESP_ROUTINGENTRY']._serialized_end=376
  _globals['_SUBSCRIBEROUTINGREQ']._serialized_start=378
  _globals['_SUBSCRIBEROUTINGREQ']._serialized_end=424
  _globals['_ROUTINGUPDATE']._serialized_start=427
  _globals['_ROUTINGUPDATE']._serialized_end=634
  _globals['_ROUTINGUPDATE_CHANGETYPE']._serialized_start=584
  _globals['_ROUTINGUPDATE_CHANGETYPE']._serialized_end=634
  _globals['_ROUTINGSERVICE']._serialized_start=637
  _globals['_ROUTINGSERVICE']._serialized_end=823
# @@protoc_insertion_point(module_scope)
